# Generated by Django 4.2.2 on 2024-01-31 06:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest', '0010_deliveryagentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.TimeField(choices=[(datetime.time(9, 0), '09:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(13, 0), '01:00 PM'), (datetime.time(15, 0), '03:00 PM'), (datetime.time(17, 0), '05:00 PM')], null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=False)),
                ('mobile', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=1000)),
                ('order_id', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=1000000)),
                ('client', models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
