# Generated by Django 4.2.2 on 2024-02-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_appointment_rejectionreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='estimatedcost',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='totalcost',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
