# Generated by Django 4.2.2 on 2024-02-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0020_addressuser_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.addressuser'),
        ),
    ]
