# Generated by Django 4.2.2 on 2024-02-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0021_rent_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliveryagentcantidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('pin', models.CharField(max_length=6)),
                ('mobile', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
