# Generated by Django 4.2.2 on 2024-02-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0025_deliveryagent_rejected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressuser',
            old_name='geolocation',
            new_name='latitude',
        ),
    ]
