# Generated by Django 4.2.2 on 2024-02-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0026_rename_geolocation_addressuser_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressuser',
            name='longitude',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
