# Generated by Django 4.2.2 on 2024-02-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0030_alter_furniturerent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniturerent',
            name='status1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='furniturerent',
            name='status',
            field=models.BooleanField(default=False, max_length=555),
        ),
    ]
