# Generated by Django 4.2.2 on 2024-03-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0031_furniturerent_status1_alter_furniturerent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='rejected',
            field=models.BooleanField(default=False, max_length=555),
        ),
    ]
