# Generated by Django 4.2.2 on 2024-03-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0032_rent_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagentprofile',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
