# Generated by Django 4.2.2 on 2024-03-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0033_alter_deliveryagentprofile_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deliveryagentcantidates',
        ),
    ]
