# Generated by Django 4.2.2 on 2024-03-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0035_deliveryagentprofile_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='pin',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
