# Generated by Django 4.2.2 on 2024-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0038_rent_deliverystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
