# Generated by Django 4.2.2 on 2024-03-26 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest', '0039_alter_appointment_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('mobile', models.IntegerField(default=0)),
                ('pet_weight', models.FloatField(default=0.0)),
                ('date', models.DateField(null=True)),
                ('time_slot', models.CharField(default='', max_length=50)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('rejectionreason', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
