# Generated by Django 4.2.2 on 2024-03-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0040_servicebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
