# Generated by Django 4.2.2 on 2024-03-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0041_servicebooking_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='estimatedcost',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
