# Generated by Django 4.2.2 on 2023-09-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_images1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_images2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_images3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_images4',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pic'),
        ),
    ]
