# Generated by Django 4.2.2 on 2023-09-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_product_dimensions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dimensions',
            new_name='breadth',
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
