# Generated by Django 4.2.2 on 2023-09-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_rename_description_category_descriptioncat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='breadth',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.AddField(
            model_name='product',
            name='measurements',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_description',
            field=models.TextField(max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, max_length=555),
        ),
    ]
