# Generated by Django 4.2.2 on 2024-01-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_product_admincontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
