# Generated by Django 4.2.2 on 2023-09-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order_addressline1_order_addressline2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ManyToManyField(to='main.order'),
        ),
    ]
