# Generated by Django 4.2.2 on 2023-10-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_payment_order_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='return1',
            field=models.BooleanField(default=False),
        ),
    ]
