# Generated by Django 4.2.2 on 2023-10-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_order_product_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
    ]
