# Generated by Django 4.2.2 on 2023-10-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_order_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcart',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
