# Generated by Django 4.2.2 on 2023-10-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_orderitem_order_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_items',
            field=models.ManyToManyField(to='main.orderitem'),
        ),
    ]
