# Generated by Django 4.2.2 on 2024-03-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_payment_order_items_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='deliverystatus',
            field=models.BooleanField(default=False),
        ),
    ]
