# Generated by Django 4.2.2 on 2023-09-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory1_name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory2_name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory3_name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
