# Generated by Django 4.2.2 on 2023-09-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_category_subcategory1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory4_name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
