# Generated by Django 4.2.2 on 2023-09-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_product_material_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
