# Generated by Django 4.2.2 on 2023-09-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Customer'), (2, 'Seller'), (3, 'Delivery'), (4, 'Admin')], default='1', null=True),
        ),
    ]
