# Generated by Django 4.2.2 on 2023-09-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
