# Generated by Django 4.2.2 on 2023-09-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rename_dimensions_product_breadth_product_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory1_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategory2_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategory3_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategory4_name',
        ),
    ]
