# Generated by Django 4.2.2 on 2023-09-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_category_description_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
