# Generated by Django 4.2.2 on 2023-09-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_subcategory_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='descriptioncat',
        ),
    ]
