# Generated by Django 4.2.2 on 2024-01-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_category_for_rent_category_for_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Customer'), (2, 'Seller'), (3, 'Delivery'), (4, 'Admin'), (5, 'Deliveryprofile')], default='1', null=True),
        ),
    ]
