# Generated by Django 4.2.2 on 2024-03-14 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0037_rename_condition_furniturerent_stock'),
        ('serviceapp', '0006_alter_delivery_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.rent'),
        ),
    ]
