# Generated by Django 4.2.2 on 2024-03-27 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0042_servicebooking_estimatedcost'),
        ('serviceapp', '0008_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentservice',
            name='service',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='rest.servicebooking'),
        ),
    ]
