# Generated by Django 4.2.2 on 2024-01-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_install'),
    ]

    operations = [
        migrations.DeleteModel(
            name='install',
        ),
    ]
