# Generated by Django 4.2.2 on 2024-01-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_install'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('condition', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='furniture_images/')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
