# Generated by Django 4.2.2 on 2024-01-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_category_for_rent_category_for_sale'),
        ('rest', '0005_furniture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniturerent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('condition', models.CharField(max_length=100)),
                ('product_images1', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('product_images2', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('product_images3', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('product_images4', models.FileField(blank=True, max_length=255, null=True, upload_to='sample/')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=False, max_length=555)),
                ('length', models.CharField(max_length=555, null=True)),
                ('width', models.CharField(max_length=555, null=True)),
                ('height', models.CharField(max_length=555, null=True)),
                ('material', models.CharField(max_length=255)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_standard', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Furniture',
        ),
    ]
