# Generated by Django 4.2.2 on 2024-01-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_deliveryagent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryagent',
            name='password',
        ),
    ]
