# Generated by Django 4.2.2 on 2024-01-30 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest', '0009_deliveryagent_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('insurance_policy_number', models.CharField(max_length=50)),
                ('insurance_expiry_date', models.DateField()),
                ('insurance_company', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('banking_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('routing_number', models.CharField(max_length=20)),
                ('max_delivery_distance', models.PositiveIntegerField()),
                ('emergency_contact', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
