# Generated by Django 4.2.2 on 2024-02-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_appointment_approved_appointment_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cost',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status1',
            field=models.BooleanField(default=False),
        ),
    ]
