# Generated by Django 4.2.2 on 2024-02-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_appointment_cost_appointment_status1'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approved_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
