# Generated by Django 4.2.2 on 2024-02-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0017_appointment_estimatedcost_appointment_totalcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
