# Generated by Django 4.2.2 on 2024-02-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0022_deliveryagentcantidates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryagentprofile',
            old_name='insurance_policy_number',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='deliveryagentprofile',
            old_name='insurance_company',
            new_name='longitude',
        ),
    ]
