# Generated by Django 4.2.2 on 2024-02-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0023_rename_insurance_policy_number_deliveryagentprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagentcantidates',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
