# Generated by Django 4.2.2 on 2024-02-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0024_deliveryagentcantidates_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
