# Generated by Django 4.2.2 on 2024-02-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0027_addressuser_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressuser',
            old_name='customer',
            new_name='user',
        ),
    ]
