# Generated by Django 4.2.2 on 2024-03-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0034_delete_deliveryagentcantidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
