# Generated by Django 4.2.2 on 2024-03-13 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0036_deliveryagentprofile_mobile_deliveryagentprofile_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniturerent',
            old_name='condition',
            new_name='stock',
        ),
    ]
