# Generated by Django 4.2.2 on 2024-03-14 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_orderitem_address'),
        ('serviceapp', '0005_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.orderitem'),
        ),
    ]
