# Generated by Django 4.2.2 on 2023-10-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_product_admincontrol'),
        ('main', '0011_order_cancel_order_return1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='accounts.product'),
        ),
    ]
