# Generated by Django 4.2.2 on 2023-10-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_product_admincontrol'),
        ('main', '0018_alter_bookcart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='products',
            field=models.ManyToManyField(to='accounts.product'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('district', models.CharField(blank=True, max_length=15, null=True)),
                ('addressline1', models.CharField(blank=True, max_length=15, null=True)),
                ('addressline2', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('aphone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True)),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.payment')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
            ],
        ),
    ]
